[package]
name = "dotrix_window"
version = "0.1.0"
edition = "2021"

[dependencies.winit]
version = "0.27.5"
features = ["serde"]

[dependencies.futures]
version = "0.3"
default-features = false
features = ["std", "executor"]

[dependencies.raw-window-handle]
version = "0.5"
