[package]
name = "dotrix_camera"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotrix_core = { path="../dotrix-core", version="0.6" }
dotrix_math = { path = "../dotrix-math", version = "0.4" }
