[package]
name = "dotrix_core"
version = "0.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotrix_types = { path="../dotrix-types", version="0.1" }
dotrix_log = { path="../dotrix-log", version="0.1" }
